"""TBX-Basic (ISO 30042) parser and writer for terminology glossaries."""

from __future__ import annotations

from pathlib import Path

from lxml import etree

from polydrive.core.models import (
    Glossary,
    LocalizedTerm,
    TermCategory,
    TermEntry,
    TermStatus,
)

_NS = "urn:iso:std:iso:30042:ed-2"
_NS_MAP = {None: _NS}
_QN = etree.QName


def _tag(local: str) -> str:
    return f"{{{_NS}}}{local}"


def _text_of(element: etree._Element | None) -> str | None:
    if element is None:
        return None
    t = element.text
    return t.strip() if t else None


def _parse_lang_sec(lang_sec: etree._Element) -> LocalizedTerm:
    lang = lang_sec.get("{http://www.w3.org/XML/1998/namespace}lang", "en")
    term_el = lang_sec.find(_tag("termSec"))
    term_text = ""
    pos: str | None = None
    definition: str | None = None

    if term_el is not None:
        t = term_el.find(_tag("term"))
        if t is not None and t.text:
            term_text = t.text.strip()
        note = term_el.find(_tag("termNote"))
        if note is not None and note.get("type") == "partOfSpeech":
            pos = _text_of(note)

    defn_el = lang_sec.find(f"{_tag('descripSec')}[@type='definition']")
    if defn_el is not None:
        definition = _text_of(defn_el)

    return LocalizedTerm(
        lang=lang,
        term=term_text,
        definition=definition,
        part_of_speech=pos,
    )


def _parse_admin(concept: etree._Element) -> tuple[TermCategory, str | None]:
    category = TermCategory.GENERAL
    note: str | None = None

    for admin_sec in concept.findall(_tag("adminSec")):
        for admin_note in admin_sec.findall(_tag("adminNote")):
            if admin_note.get("type") == "termCategory":
                raw = _text_of(admin_note)
                if raw:
                    try:
                        category = TermCategory(raw)
                    except ValueError:
                        pass
        raw_note = admin_sec.find(_tag("note"))
        if raw_note is not None:
            note = _text_of(raw_note)

    return category, note


def parse_tbx(file_path: Path) -> Glossary:
    """Parse a TBX-Basic XML file into a Glossary model."""
    tree = etree.parse(str(file_path))
    root = tree.getroot()

    title = ""
    header = root.find(f".//{_tag('titleStmt')}/{_tag('title')}")
    if header is not None:
        title = _text_of(header) or ""

    source_lang = root.get("{http://www.w3.org/XML/1998/namespace}lang", "en")

    entries: list[TermEntry] = []
    for concept in root.findall(f".//{_tag('conceptEntry')}"):
        entry_id = concept.get("id", "")

        subject = ""
        subj_el = concept.find(f"{_tag('descripSec')}[@type='subjectField']")
        if subj_el is not None:
            subject = _text_of(subj_el) or ""

        category, note = _parse_admin(concept)

        translations: list[LocalizedTerm] = []
        for lang_sec in concept.findall(_tag("langSec")):
            translations.append(_parse_lang_sec(lang_sec))

        entries.append(
            TermEntry(
                id=entry_id,
                subject=subject,
                category=category,
                note=note,
                translations=translations,
            )
        )

    return Glossary(
        id=file_path.stem,
        title=title,
        source_lang=source_lang,
        entries=entries,
    )


def write_tbx(glossary: Glossary, file_path: Path) -> None:
    """Write a Glossary model to a TBX-Basic XML file."""
    root = etree.Element(_tag("tbx"), nsmap=_NS_MAP)
    root.set("type", "TBX-Basic")
    root.set("style", "dca")
    root.set("{http://www.w3.org/XML/1998/namespace}lang", glossary.source_lang)

    header = etree.SubElement(root, _tag("tbxHeader"))
    file_desc = etree.SubElement(header, _tag("fileDesc"))
    title_stmt = etree.SubElement(file_desc, _tag("titleStmt"))
    title_el = etree.SubElement(title_stmt, _tag("title"))
    title_el.text = glossary.title or glossary.id
    source_desc = etree.SubElement(file_desc, _tag("sourceDesc"))
    p = etree.SubElement(source_desc, _tag("p"))
    p.text = "Generated by PolyDrive"

    text = etree.SubElement(root, _tag("text"))
    body = etree.SubElement(text, _tag("body"))

    for entry in glossary.entries:
        concept = etree.SubElement(body, _tag("conceptEntry"))
        concept.set("id", entry.id)

        for lt in entry.translations:
            lang_sec = etree.SubElement(concept, _tag("langSec"))
            lang_sec.set("{http://www.w3.org/XML/1998/namespace}lang", lt.lang)

            term_sec = etree.SubElement(lang_sec, _tag("termSec"))
            term_el = etree.SubElement(term_sec, _tag("term"))
            term_el.text = lt.term

            if lt.part_of_speech:
                note = etree.SubElement(term_sec, _tag("termNote"))
                note.set("type", "partOfSpeech")
                note.text = lt.part_of_speech

            if lt.definition:
                defn = etree.SubElement(lang_sec, _tag("descripSec"))
                defn.set("type", "definition")
                defn.text = lt.definition

        if entry.subject:
            subj = etree.SubElement(concept, _tag("descripSec"))
            subj.set("type", "subjectField")
            subj.text = entry.subject

        admin = etree.SubElement(concept, _tag("adminSec"))
        cat_note = etree.SubElement(admin, _tag("adminNote"))
        cat_note.set("type", "termCategory")
        cat_note.text = entry.category.value

        if entry.note:
            n = etree.SubElement(admin, _tag("note"))
            n.text = entry.note

    tree = etree.ElementTree(root)
    etree.indent(tree, space="  ")
    tree.write(
        str(file_path),
        xml_declaration=True,
        encoding="UTF-8",
        pretty_print=True,
    )
